# permissions for end users to view cronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-viewer-role
rules:
- apiGroups:
  - batch.linkinghack.com
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.linkinghack.com
  resources:
  - cronjobs/status
  verbs:
  - get
